<?php

// Create User
const NO_ERROR = -1;
const MISSING_USERNAME = 0;
const USERNAME_TAKEN = 1;
const MISSING_PWD = 2;
const MISSING_CONF = 3;
const PWD_NO_MATCH = 4;
const USER_NOT_EXISTING = 5;
const WRONG_PWD = 6;
const USERNAME_TOO_LONG = 7;
const MISSING_CAPTCHA = 8;
const BAD_CAPTCHA = 9;
const MISSING_GAME_NAME = 10;
const GAME_NOT_FOUND = 11;
const MISSING_GOAL_TITLE = 12;
const GOAL_TOO_LONG = 13;
const GOAL_DESC_TOO_LONG = 14;
const GAME_ALREADY_EXISTS = 15;
